[project]
name = "mercatracker"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "tqdm",
    "requests",
    "certifi",
    "bs4",
    "yarl",
    "dotenv",
    "lxml",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"